/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler */

#ifndef _Included_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
#define _Included_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
 * Method:    Test0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Test0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
 * Method:    ConsoleClear0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_ConsoleClear0
  (JNIEnv *, jclass);

/*
 * Class:     io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
 * Method:    Test1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Test1
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler
 * Method:    Test2
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Test2
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
