language: java
sudo: false
jdk:
  - oraclejdk8
compiler:
  - gcc
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
  - jdk_switcher use oraclejdk8
  - gcc -version
  - gcc -I"$JAVA_HOME/include/linux" -l"Ruskit.Test" -o $TRAVIS_BUILD_DIR/libRuskitSendboxHandler.so -shared -fPIC Ruskit.Test/RuskitSendboxHandler.cpp
