language: java
sudo: required
jdk:
  - oraclejdk8
compiler:
  - gcc
env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
script:
  - jdk_switcher use oraclejdk8
  - gcc --version
  - gcc -I"$JAVA_HOME/include/linux" -I"$JAVA_HOME/include" -I"$TRAVIS_BUILD_DIR/Ruskit.Test" -o $TRAVIS_BUILD_DIR/libRuskitSendboxHandler.so -shared -fPIC $TRAVIS_BUILD_DIR/Ruskit.Test/RuskitSendboxHandler.cpp
  - nm $TRAVIS_BUILD_DIR/libRuskitSendboxHandler.so | grep say
  - mv $TRAVIS_BUILD_DIR/libRuskitSendboxHandler.so src/main/resources/
  - mvn install
before_install:
  - apt-get install binutils
