/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Companion */

#ifndef _Included_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Companion
#define _Included_io_github_ruskonert_ruskit_sendbox_RuskitSendboxHandler_Companion
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
